- hosts: all

  sudo: yes

  vars:

    redis_version:  2.8.12
    master:
      name:         integrationtests
      ip:           192.168.50.40
      port:         6379
    sentinel:
      port:         26379

  tasks:

    - name: Download redis
      get_url: url=http://download.redis.io/releases/redis-{{redis_version}}.tar.gz dest=/tmp

    - name: Untar PSRedis
      command: chdir=/tmp creates=redis-{{redis_version}} tar -xzf redis-{{redis_version}}.tar.gz

    - name: Install PSRedis
      command: creates=/usr/local/bin/redis-server chdir=/tmp/redis-{{redis_version}} make install

    - name: Create user redis
      user: name=redis system=yes home=/var/lib/redis shell=/bin/false

    - name: Creates redis configuration directory
      file: path=/etc/redis state=directory owner=redis

    - name: Configure sentinel
      template: src=files/conf/sentinel.j2 dest=/etc/redis/sentinel.conf owner=redis

    - name: configure example configuration for sentinel
      template: src=files/conf/sentinel.j2 dest=/etc/redis/sentinel.example.conf owner=redis

    - name: Configure Upstart for Sentinel
      template: src=files/upstart/sentinel.j2 dest=/etc/init/sentinel.conf
      notify: Restart Sentinel

    - name: Start Sentinel
      service: name=sentinel state=started

  handlers:

      - name: Restart Sentinel
        service: name=sentinel state=restarted